name: slim_project
services:
    php:
        build:
            context: docker/php
        container_name: php84
        volumes:
            - ./:var/www/html
        networks:
            - php_network
    nginx:
        image: nginx:1.27-alpine3.21
        container_name: nginx_server
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:var/www/html
        ports:
            - "8080:80"
        networks:
            - php_network
        depends_on:
            - php
    mysql:
        image: 'mysql:8.4.3'
        container_name: mysql
        ports:
            - "3306:3306"
        networks:
            - php_network
        environment:
            - MYSQL_ROOT_PASSWORD: root
            - MYSQL_DATABASE: 'slim_framework'
            - MYSQL_ALLOW_EMPTY_PASSWORD: 1
networks:
    php_network:
        driver: bridge
        name: php_network
