services:
    server:
        image: nginx:1.27.4-alpine-slim
        ports:
            - "8000:80"
        volumes:
            - /:var/www/html
    php:
        build:
            context: Dockerfile
    database:
        image: 'mysql/mysql-server:8.0'
        # nginx:1.27.4-alpine-slim
        # mysql/mysl-server:8.0
